name: clinic_app
description: obesity

version: 1.0.0+1

environment:
   sdk: '>=2.6.0 <3.0.0'

dependencies:
   flutter:
      sdk: flutter
   flutter_localizations:
      sdk: flutter
   # flutter_cupertino_localizations: ^1.0.1

   # The following adds the Cupertino Icons font to your application.
   # Use with the CupertinoIcons class for iOS style icons.
   cupertino_icons: ^0.1.2
   provider: ^4.0.4
   shared_preferences:
   http: ^0.12.0+4
   bottom_navy_bar: ^5.3.2
   transparent_image: ^1.0.0
   cached_network_image: ^2.0.0
   graphql_flutter: ^3.0.0
   image_picker: ^0.6.3+4
   dospace: ^0.12.12
   shimmer: ^1.0.1
   flutter_ffmpeg: ^0.2.10
   mime: ^0.9.6+3
   toast: ^0.1.5
   flutter_native_image: ^0.0.5+2
   timeago: ^2.0.26
   carousel_slider: ^1.4.1
   video_player:
   photo_view: ^0.9.2
   country_code_picker: ^1.1.7
   path_provider: ^1.6.5
   firebase_core: ^0.4.4+3
   firebase_messaging: ^6.0.13
   font_awesome_flutter: ^8.8.1
   gender_selection: ^1.0.0
   flutter_svg: ^0.17.3+1
   pinput: ^0.1.10
   flutter_slidable: ^0.5.4
   chips_choice: ^1.1.0

dev_dependencies:
   flutter_test:
      sdk: flutter
   intl_translation: ^0.17.9
   flutter_launcher_icons: ^0.7.4 

flutter_icons:
  image_path: "assets/images/mill.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
   uses-material-design: true

   # The following line ensures that the Material Icons font is
   # included with your application, so that you can use the icons in
   # the material Icons class.
   # uses-material-design: true

   # To add assets to your application, add an assets section, like this:
   assets:
      - assets/images/
   # An image asset can refer to one or more resolution-specific "variants", see
   # https://flutter.dev/assets-and-images/#resolution-aware.
   # For details regarding adding assets from package dependencies, see
   # https://flutter.dev/assets-and-images/#from-packages
   # To add custom fonts to your application, add a fonts section here,
   # in this "flutter" section. Each entry in this list should have a
   # "family" key with the font family name, and a "fonts" key with a
   # list giving the asset and other descriptors for the font. For
   # example:
   # fonts:
   #   - family: Schyler
   #     fonts:
   #       - asset: fonts/Schyler-Regular.ttf
   #       - asset: fonts/Schyler-Italic.ttf
   #         style: italic
   #   - family: Trajan Pro
   #     fonts:
   #       - asset: fonts/TrajanPro.ttf
   #       - asset: fonts/TrajanPro_Bold.ttf
   #         weight: 700
   #
   # For details regarding fonts from package dependencies,
   # see https://flutter.dev/custom-fonts/#from-packages
